### PR TITLE
Fix stylization of 'WildFly' especially in publicly visible strings.

### PR DESCRIPTION
**Pull request by rhusar**
The change in `src/main/java/org/wildfly/bot/model/RuntimeConstants.java` is the crux of the issue.

### CODE REVIEW

**Comment by rhusar** [comment]
@xstefank Do you know who manages this project? This has been open since June and the bot is still mangling our project name on every PR... ;)

**Comment by xstefank** [comment]
@petrberan

**Comment by rhusar** [comment]
@petrberan still the owner? any reason on stalling this?

**Comment by rhusar** [comment]
> No valid reason for that, sorry about the wait @rhusar

Haha, no worries, too many GitHub notifications I know that very well :-)

**Review by petrberan — APPROVED** [review]
LGTM

**Comment by rhusar** [comment]
Thanks!

**Pull request merged**
